name: Close Issue
description: Close an issue

inputs:
  message:
    description: "Comment Message"
    required: true
  issue:
    description: "Issue Number"
    required: false
    default: ${{ github.event.issue.number }}
  reason:
    description: "Reason for closing: {completed|not planned}"
    required: false
    default: "completed"
  token:
    description: "Token used for GitHub API calls"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh issue close ${{ inputs.issue }} \
        -r ${{ inputs.reason }} \
        -c "${{ inputs.message }}"
      shell: bash
