---
name: GitHub team request
description: Request a new GitHub team for the current organization. The requesting user will automatically added as a maintainer for the new team.
title: "[Github Team Request]"
labels: [github-team-request]
body:
  - type: input
    attributes:
      label: Name
      description: Name of the team
    validations:
      required: true
  - type: input
    attributes:
      label: Description
      description: Description of the team
    validations:
      required: false