---
name: Repo request
description: Request a new repository in your organization.
title: "[Repo Request]"
labels: [repo-request]
body:
  - type: dropdown
    attributes:
      label: Visibility
      options:
        - public
        - internal
        - private
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Name
      description: Name of the repository
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Team
      options:
        - Admins
        - Backstreetboys - Xpirit boyband!
        - DevOps-Team - DevOps-Team
        - Developer
        - Die3Lustigen4 - hahaha
        - GitHub Demo - The technical demo
        - Goofies Band - The band of Goofy.
        - JS-Developers - Team for all the JS-Developers
        - Justice League - A great team
        - Justice League22 - A great team
        - NSync - :D
        - Repo-Admins - All about the Repo-Admins
        - Test - A great team
        - The Avengers - Epic crew of the Avengers.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Language
      options:
        - c#
        - python
        - terraform
    validations:
      required: false
  - type: input
    attributes:
      label: Topics
      description: comma-separated array of topics to add
    validations:
      required: false
