name: Repo request
description: Request a new Repository in your organization.
title: "[Repo Request] "
labels: [repo-request]
body:
  - type: input
    attributes:
      label: Name
      description: Name of the repository
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Company
      options: []
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Team
      options: []
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Project
      options: []
    validations:
      required: true
