---
name: Repo request
description: Request a new Repository in your organization.
title: "[Repo Request] "
labels: [repo-request]
body:
  - type: input
    attributes:
      label: Name
      description: Name of the repository
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Company
      options:
        - MariBo
        - Xpirit
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Team
      options:
        - MeOnly
        - Team 1
        - Team 2
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Project
      options:
        - project 1
        - project 2
        - project 3
        - project 4
        - project 5
        - project 6
    validations:
      required: true
