---
name: Repo deletion
description: Request deletion of a repository in your organization.
title: "[Repo Deletion] "
labels: [repo-deletion]
body:
  - type: input
    attributes:
      label: Name
      description: Full name of the repository
    validations:
      required: true
