name: Add Repository Topics
description: Add a list of topics to a repository

inputs:
  owner:
    description: "Repository owner"
    required: true
  repository:
    description: "Repository name"
    required: true
  topics:
    description: "JSON array of topics"
    required: true
  token:
    description: "Token used for GitHub API calls"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - id: get-topics
      run: |
        topics="$(echo ${{ inputs.topics }} | jq '. | join (",")' | sed -e 's/^[[:space:]]*//')" >> "$GITHUB_OUTPUT"
      shell: bash
    - if: ${{ steps.get-topics.outputs.topics != '' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh repo edit --add-topic ${{ steps.get-topics.outputs.topics }}
      shell: bash
