name: Add Repository Topics
description: Add a list of topics to a repository

inputs:
  owner:
    description: "Repository owner"
    required: true
  repository:
    description: "Repository name"
    required: true
  topics:
    description: "Comma-separated list of topics"
    required: true
  token:
    description: "Token used for GitHub API calls"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.topics != '' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh repo edit ${{ inputs.owner}}/${{ inputs.repository }} \
          --add-topic ${{ inputs.topics }}
      shell: bash
