name: Create New GitHub Team

on:
  workflow_call:
    inputs:
      team_name:
        description: "Team Name"
        required: true
        type: string
      description:
        description: "Team Description"
        required: false
        type: string
    outputs:
      team_url:
        description: "The URL of the created team"
        value: ${{ jobs.create-github-team.outputs.team_url }}
  workflow_dispatch:
    inputs:
      team_name:
        description: "Team Name"
        required: true
        type: string
        default: "MyTestTeam"
      description:
        description: "Team Description"
        required: true
        type: string
        default: "MyTestTeamDescription"

permissions:
  actions: write
  contents: read
  issues: write

env:
  DEFAULT_BRANCH: main
  TEAM_NAME: ${{ inputs.team_name }}
  DESCRIPTION: ${{ inputs.description }}
  ORGANIZATION: ${{ vars.ORGANIZATION }}

jobs:
  create-github-team:
    name: "Create GitHub Team"
    runs-on: ubuntu-latest
    environment: github-team
    concurrency: create-${{ inputs.team_name }}
    outputs:
      team_url: ${{ steps.create-github-team.outputs.team_url }}
    steps:
      - name: Get Token
        id: get-workflow-token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Create GitHub Team
        id: create-github-team
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
        run: |
          JSON_RESULT=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/$ORGANIZATION/teams \
            -f name='${{ env.TEAM_NAME }}' \
            -f description='${{ env.DESCRIPTION }}' \
            -f permission='push' \
            -f notification_setting='notifications_enabled' \
            -f privacy='closed')
          echo "team_url=$(echo $JSON_RESULT | jq .html_url)" >> "$GITHUB_OUTPUT"
