name: Handle Repo Deletion

on:
  workflow_call:

jobs:
  notify:
    name: "Notify Deletion Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
    steps:
      - uses: actions/checkout@v4
      - name: Add Comment To Issue
        uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} a [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) was started to handle your request"

  parse:
    name: "Parse Deletion Issue"
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.repo-name.outputs.repo_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Parse Issue Form into JSON
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Repo Name
        id: repo-name
        env:
          JSON: ${{ steps.parse.outputs.data }}
        run: |
          echo "repo_name=$(echo $JSON | jq -r '.name.text')" >> "$GITHUB_OUTPUT"
      - name: Summarize
        env:
          REPO_ORG: ${{ vars.ORGANIZATION }}
          REPO_NAME: ${{ steps.repo-name.outputs.repo_name }}
          USER: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          {
            echo "# Request Repo Deletion"
            echo "Repository: [$REPO_NAME](${GITHUB_SERVER_URL}/${REPO_ORG}/${REPO_NAME})"
            echo "User: @${USER}"
            echo "Issue: [#${ISSUE_NUMBER}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER})"
          } >> $GITHUB_STEP_SUMMARY

  handle:
    needs:
      - parse
    uses: ./.github/workflows/repo-deletion.yml
    with:
      repo_name: ${{ needs.parse.outputs.repo_name }}
    secrets: inherit

  comment:
    if: ${{ failure() }}
    needs:
      - notify
      - parse
      - handle
    name: "Comment Deletion Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
    steps:
      - uses: actions/checkout@v4
      - name: Add Comment To Issue
        uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} the repository deletion failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details"

  close:
    if: ${{ success() }}
    needs:
      - notify
      - parse
      - handle
    name: "Close Deletion Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
    steps:
      - uses: actions/checkout@v4
      - name: Close Issue With Comment
        uses: ./.github/actions/close-issue
        with:
          message: "@${USER} your repository was successfully deleted"
