name: Handle GitHub Team Request

on:
  workflow_call:

env:
  USER: ${{ github.event.issue.user.login }}

jobs:
  notify:
    name: "Notify Request Issue"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} a [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) was started to handle your request"

  parse:
    name: "Parse Request Issue"
    runs-on: ubuntu-latest
    outputs:
      team_name: ${{ steps.attributes.outputs.team_name }}
      description: ${{ steps.attributes.outputs.description }}
      maintainer: ${{ steps.attributes.outputs.maintainer }}
      parent_team: ${{ steps.attributes.outputs.parent_team }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Parse Issue Form into JSON
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Attributes
        id: attributes
        env:
          JSON: ${{ steps.parse.outputs.data }}
        run: |
          echo "team_name=$(echo $JSON | jq -r '.name.text')" >> "$GITHUB_OUTPUT"
          echo "description=$(echo $JSON | jq -r '.description.text')" >> "$GITHUB_OUTPUT"
          echo "maintainer=${USER}" >> "$GITHUB_OUTPUT"
          echo "parent_team=$(echo $JSON | jq -r '.parent.text' | sed -E 's/ -.*//')" >> "$GITHUB_OUTPUT"

  handle:
    needs:
      - parse
    uses: ./.github/workflows/github-team-creation.yml
    with:
      team_name: ${{ needs.parse.outputs.team_name }}
      description: ${{ needs.parse.outputs.description }}
      maintainer: ${{ needs.parse.outputs.maintainer }}
      parent_team: ${{ needs.parse.outputs.parent_team }}
    secrets: inherit

  comment:
    if: failure()
    needs:
      - notify
      - parse
      - handle
    name: "Comment Request Issue"
    runs-on: ubuntu-latest
    env:
      TEAM_URL: ${{ needs.handle.outputs.team_url }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} the team provisioning failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details"

  close:
    if: success()
    needs:
      - notify
      - parse
      - handle
    name: "Close Request Issue"
    runs-on: ubuntu-latest
    env:
      TEAM_URL: ${{ needs.handle.outputs.team_url }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/close-issue
        with:
          message: "@${USER} your team was created and is now accessible here: $TEAM_URL"
