name: Handle Issue

on:
  issues:
    types: [labeled]

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  create-repo:
    if: github.event.label.name == 'repo-request'
    uses: ./.github/workflows/handle-repo-request.yml
  delete-repo:
    if: github.event.label.name == 'repo-deletion'
    uses: ./.github/workflows/handle-repo-deletion.yml
