name: Handle Repo Request

on:
  workflow_call:

jobs:
  notify:
    name: "Notify Request Issue"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/comment-issue
        with:
          message: "@${{ github.event.issue.user.login }} a [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) was started to handle your request"

  parse:
    name: "Parse Request Issue"
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.repo-name.outputs.project_name }}
      repo_name: ${{ steps.repo-name.outputs.repo_name }}
      visibility: ${{ steps.attributes.outputs.visibility }}
      language: ${{ steps.attributes.outputs.language }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Parse Issue Form into JSON
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Repo Name
        id: repo-name
        env:
          JSON: ${{ steps.parse.outputs.data }}
          LC_ALL: "C"
        run: |
          function github_name() {
            echo $1 | tr '[:upper:]' '[:lower:]' | sed -r 's/[^a-z0-9ß-ü \-]*//g' | sed -e 's/ä/ae/g' -e 's/ö/oe/g' -e 's/ü/ue/g' -e 's/ß/ss/g' | sed -r 's/[\t ]+/-/g'
          }
          TEAM=$(github_name "$(echo $JSON | jq -r '.team.text' | sed -E 's/ -.*//')")
          NAME=$(github_name "$(echo $JSON | jq -r '.name.text')")
          echo "project_name"="${NAME}" >> "$GITHUB_OUTPUT"
          echo "repo_name=${TEAM}-${NAME}" >> "$GITHUB_OUTPUT"
      - name: Get Attrbutes
        id: attributes
        env:
          JSON: ${{ steps.parse.outputs.data }}
        run: |
          echo "visibility=$(echo $JSON | jq -r '.visibility.text')" >> "$GITHUB_OUTPUT"
          echo "language=$(echo $JSON | jq -r '.language.text')" >> "$GITHUB_OUTPUT"

  handle:
    needs:
      - parse
    uses: ./.github/workflows/repo-creation.yml
    with:
      project_name: ${{ needs.parse.outputs.project_name }}
      repo_name: ${{ needs.parse.outputs.repo_name }}
      visibility: ${{ needs.parse.outputs.visibility }}
      language: ${{ needs.parse.outputs.language }}
    secrets: inherit

  comment:
    if: ${{ failure() }}
    needs:
      - notify
      - parse
      - handle
    name: "Comment Request Issue"
    runs-on: ubuntu-latest
    env:
      REPO_URL: ${{ needs.handle.outputs.repo_url }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/comment-issue
        with:
          message: "@${{ github.event.issue.user.login }} the repository provisioning failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details"

  close:
    if: ${{ success() }}
    needs:
      - notify
      - parse
      - handle
    name: "Close Request Issue"
    runs-on: ubuntu-latest
    env:
      REPO_URL: ${{ needs.handle.outputs.repo_url }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./.github/actions/close-issue
        with:
          message: "@${{ github.event.issue.user.login }} your repository was created and is now accessible here: $REPO_URL"
