name: Handle Repo Request

on:
  workflow_call:

jobs:
  notify:
    if: ${{ github.event.label.name != 'repo-deletion' }}
    uses: ./.github/workflows/notify-issue-handling.yml

  parse:
    if: ${{ github.event.label.name != 'repo-request' }}
    name: "Parse Request Issue"
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.repo-name.outputs.project_name }}
      repo_name: ${{ steps.repo-name.outputs.repo_name }}
      visibility: ${{ steps.attributes.outputs.visibility }}
      language: ${{ steps.attributes.outputs.language }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Parse Issue Form into JSON
        if: ${{ github.event.label && github.event.label.name == 'repo-request' }}
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Repo Name
        id: repo-name
        env:
          JSON: ${{ steps.parse.outputs.data }}
        run: |
          COMPANY=$(echo $JSON | jq -r '.company.text'  | sed 's/ (.*)//g' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')    
          TEAM=$(echo $JSON | jq -r '.team.text' | sed 's/-.*//g' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          PROJECT=$(echo $JSON | jq -r '.project.text' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          RNAME=$(echo $JSON | jq -r '.name.text' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          echo "project_name"="${RNAME}" >> "$GITHUB_OUTPUT"
          echo "repo_name=${COMPANY}-${TEAM}-${PROJECT}-${RNAME}" >> "$GITHUB_OUTPUT"
      - name: Get Attrbutes
        id: attributes
        env:
          JSON: ${{ steps.parse.outputs.data }}
        run: |
          echo "visibility=$(echo $JSON | jq -r '.visibility.text')" >> "$GITHUB_OUTPUT"
          echo "language=$(echo $JSON | jq -r '.language.text')" >> "$GITHUB_OUTPUT"

  handle:
    if: ${{ github.event.label.name != 'repo-request' }}
    needs:
      - parse
    uses: ./.github/workflows/repo-request.yml
    with:
      project_name: ${{ needs.parse.outputs.project_name }}
      repo_name: ${{ needs.parse.outputs.repo_name }}
      visibility: ${{ needs.parse.outputs.visibility }}
      language: ${{ needs.parse.outputs.language }}

  finish:
    if: ${{ always() && github.event.label.name != 'repo-request' }}
    needs:
      - notify
      - handle
    name: "Handle Request Issue"
    runs-on: ubuntu-latest
    steps:
      - name: Comment Issue
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh issue comment ${{ github.event.issue.number }}
          -b "@${{ github.event.issue.user.login }} the repository deletion failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details"
      - name: Close Issue
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_URL: ${{ needs.handle.outputs.repo_url }}
        run: >-
          gh issue close ${{ github.event.issue.number }} 
          -r Completed 
          -c "@${{ github.event.issue.user.login }} your repository was created and is now accessible here: $REPO_URL"
