name: Handle Issue

on:
  issues:
    types: [labeled]

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  repo-request:
    name: "Request a repository"
    if: github.event.label.name == 'repo-request'
    uses: ./.github/workflows/handle-repo-request.yml
    secrets: inherit
  repo-deletion:
    name: "Delete a repository"
    if: github.event.label.name == 'repo-deletion'
    uses: ./.github/workflows/handle-repo-deletion.yml
    secrets: inherit
  team-request:
      name: "Request a team"
      if: github.event.label.name == 'team-request'
      uses: ./.github/workflows/handle-team-request.yml
      secrets: inherit
