name: Handle Repo Request

on:
  workflow_call:

jobs:
  notify:
    name: "Notify Request Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Add Comment To Issue
        uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} a [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) was started to handle your request"

  parse:
    name: "Parse Request Issue"
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.attributes.outputs.project_name }}
      team_slug: ${{ steps.attributes.outputs.team_slug }}
      repo_name: ${{ steps.attributes.outputs.repo_name }}
      visibility: ${{ steps.attributes.outputs.visibility }}
      language: ${{ steps.attributes.outputs.language }}
      topics: ${{ steps.attributes.outputs.topics }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Parse Issue Form into JSON
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Attrbutes
        id: attributes
        env:
          JSON: ${{ steps.parse.outputs.data }}
          LC_ALL: "C"
        run: |
          function github_name() {
            echo $1 \
            | tr '[:upper:]' '[:lower:]' \
            | sed -r 's/[^a-z0-9ß-ü \-]*//g' \
            | sed -e 's/ä/ae/g' -e 's/ö/oe/g' -e 's/ü/ue/g' -e 's/ß/ss/g' \
            | sed -r 's/[\t ]+/-/g' \
            | sed -r 's/[-]+/-/g'
          }
          function github_name_array() {
            array=""
            for item in $(echo $1 | tr " " "-" | tr "," " "); do
              array+="$(github_name $item),"
            done
            echo $array | sed 's/.$//'
          }
          TEAM=$(github_name "$(echo $JSON | jq -r '.team.text' | sed -E 's/ -.*//')")
          NAME=$(github_name "$(echo $JSON | jq -r '.name.text')")
          TOPICS=$(github_name_array "$(echo $JSON | jq -r '.topics.text')")
          echo "project_name=$NAME" >> "$GITHUB_OUTPUT"
          echo "team_slug=$TEAM" >> "$GITHUB_OUTPUT"
          echo "repo_name=${TEAM}-${NAME}" >> "$GITHUB_OUTPUT"
          echo "topics=$TOPICS" >> "$GITHUB_OUTPUT"
          echo "visibility=$(echo $JSON | jq -r '.visibility.text')" >> "$GITHUB_OUTPUT"
          echo "language=$(echo $JSON | jq -r '.language.text')" >> "$GITHUB_OUTPUT"

  handle:
    needs:
      - parse
    uses: ./.github/workflows/repo-creation.yml
    with:
      project_name: ${{ needs.parse.outputs.project_name }}
      repo_name: ${{ needs.parse.outputs.repo_name }}
      visibility: ${{ needs.parse.outputs.visibility }}
      language: ${{ needs.parse.outputs.language }}
      topics: ${{ needs.parse.outputs.topics }}
    secrets: inherit

  comment:
    if: ${{ failure() }}
    needs:
      - notify
      - parse
      - handle
    name: "Comment Request Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Add Comment To Issue
        uses: ./.github/actions/comment-issue
        with:
          message: "@${USER} the repository provisioning failed...check the [workflow]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) for details"

  close:
    if: ${{ success() }}
    needs:
      - notify
      - parse
      - handle
    name: "Close Request Issue"
    runs-on: ubuntu-latest
    env:
      USER: ${{ github.event.issue.user.login }}
      REPO_URL: ${{ needs.handle.outputs.repo_url }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Close Issue With Comment
        uses: ./.github/actions/close-issue
        with:
          message: "@${USER} your repository was created and is now accessible here: $REPO_URL"
