name: Create new repo based on issue

on:
 issues:
    types: [labeled]

jobs:
  create-repos-from-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Show parsed data JSON
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "${{ steps.parse.outputs.payload.Name }}"
          gh repo create ${{ steps.parse.outputs.payload.Name }} --public
