name: Create new repo for repo request 

on:
 issues:
    types: [labeled]
    
permissions:
  contents: read
  issues: write

jobs:
  create-repos-from-issue:
    if: ${{ github.event.label.name == 'repo-request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Create repo
        id: create-repo
        shell: bash
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          name=$(echo '${{ steps.parse.outputs.payload }}' | jq -r .Name)
          url=$(gh repo create xpirit-training/$name --public)
          echo "repo_url=$url" >> "$GITHUB_OUTPUT"
      - name: Create comment and close issue on success
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue close ${{ github.event.issue.number }} -r Completed -c "@${{ github.event.issue.user.login }} your repository was created and is now accessible here: ${{ steps.create-repo.outputs.repo_url }}"
      - name: Create comment on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "@${{ github.event.issue.user.login }} there were some problems provisioning your repo. Please reach out to your org owner for additional help. Thank you."  
          
