name: Create New Repo

on:
  workflow_call:
    inputs:
      project_name:
        description: "Project Name"
        required: true
        type: string
      repo_name:
        description: "Repo Name"
        required: true
        type: string
      visibility:
        description: "Repo Visibility"
        required: true
        type: string
      language:
        description: "Language Template"
        required: true
        type: string
      delete-repo:
        description: "Delete repository at the end of the workflow run"
        required: false
        type: boolean
        default: false
    outputs:
      repo_url:
        description: "The URL of the created repo"
        value: ${{ jobs.create-repo.outputs.repo_url }}
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project Name"
        required: true
        type: string
        default: "TestProject"
      repo_name:
        description: "Repo Name"
        required: true
        type: string
        default: "TestCompany-TestTeam-TestProject"
      visibility:
        description: "Repo Visibility"
        required: true
        type: choice
        options:
          - public
          - internal
          - private
        default: "public"
      language:
        description: "Language Template"
        required: true
        type: string
        default: "terraform"
      delete-repo:
        description: "Delete repository at the end of the workflow run"
        required: false
        type: boolean
        default: false

permissions:
  actions: write
  contents: read
  issues: write

env:
  DEFAULT_BRANCH: main
  REPO_NAME: ${{ inputs.repo_name }}
  REPO_OWNER: ${{ vars.ORGANIZATION }}
  PROJECT_NAME: ${{ inputs.project_name }}
  LANGUAGE: ${{ inputs.language }}
  VISIBILITY: ${{ inputs.visibility }}

jobs:
  cache-templates:
    name: "Cache Templates"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Cache Template Files
        id: cache-template-files
        uses: actions/cache@v3
        with:
          path: ./templates
          key: templates-${{ github.run_id }}

  create-repo:
    name: "Create Repo"
    needs: cache-templates
    runs-on: ubuntu-latest
    outputs:
      repo_url: ${{ steps.create-repo.outputs.repo_url }}
    steps:
      - name: Validate Repo Name
        run: |
          # shall not be empty
          if [ -z $REPO_NAME ]; then exit 1; fi
          # shall be alphanumeric and minus only
          if [[ "$REPO" =~ [^\-a-zA-Z0-9] ]]; then exit 1; fi
          # shall not start with minus
          if [[ "$REPO" == -* ]]; then exit 1; fi
          # shall not end with minus
          if [[ "$REPO" == *- ]]; then exit 1; fi
      - name: Restore Cached Template Files
        id: restore-cached-template-files
        uses: actions/cache@v3
        with:
          path: ./templates
          key: templates-${{ github.run_id }}
      - name: Get Token
        id: get-workflow-token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Create Repo
        id: create-repo
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
        run: |
          REPO_URL=$(gh repo create $REPO_OWNER/$REPO_NAME --$VISIBILITY --clone)
          echo "repo_url=$REPO_URL" >> "$GITHUB_OUTPUT"
      - name: Copy Files
        working-directory: ./${{ inputs.repo_name }}
        run: |
          cp -r ../templates/common/* .
          cp -r ../templates/languages/$LANGUAGE/* .
      - name: Templating Using Jinja
        working-directory: ./${{ inputs.repo_name }}
        run: |
          pip install jinja-cli         
          find . -type f -exec sh -c 'jinja -E PROJECT_NAME -o $0 $0' {} \;
      - name: Commit & Push Files
        working-directory: ./${{ inputs.repo_name }}
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
          CI_COMMIT_MESSAGE: "chore(org): Initial commit"
        run: |
          gh auth setup-git
          git config user.name '${{ vars.CI_COMMIT_USER }}'
          git config user.email '${{ vars.CI_COMMIT_USER_MAIL }}'
          git checkout -b $DEFAULT_BRANCH
          git add -A
          git commit -m "$CI_COMMIT_MESSAGE"
          git push --set-upstream origin $DEFAULT_BRANCH
      - name: Delete Repo
        if: ${{ failure() || github.event.inputs.delete-repo == 'true' }}
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
        run: |
          gh repo delete $REPO_OWNER/$REPO_NAME --yes
