name: Create new repo for repo request 

on:
 issues:
    types: [labeled]
    
permissions:
  contents: read
  issues: write

jobs:
  create-repos-from-issue:
    if: ${{ github.event.label.name == 'repo-request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - name: Get Repo Name
        id: generate-repo-name
        shell: bash
        run: |
          COMPANY=$(jq -r '.Company' ${{ steps.parse.outputs.data }} | sed 's/ (.*)//g' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')    
          TEAM=$(jq -r '.Team' ${{ steps.parse.outputs.data }} | sed 's/-.*//g' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          PROJECT=$(jq -r '.Project' ${{ steps.parse.outputs.data }} | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          RNAME=$(jq -r '.Name' ${{ steps.parse.outputs.data }} | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
          echo "name=${COMPANY}-${TEAM}-${PROJECT}-${RNAME}" >> "$GITHUB_OUTPUT"
      - name: Validate Repo Name
        shell: bash
        env:
          REPO_NAME: ${{ steps.generate-repo-name.outputs.name }}
        run: |
          # shall not be empty
          if [ -z $REPO_NAME ]; then exit 1; fi
          # shall be alphanumeric and minus only
          if [[ "$REPO" =~ [^\-a-zA-Z0-9] ]]; then exit 1; fi
          # shall not start with minus
          if [[ "$REPO" == -* ]]; then exit 1; fi
          # shall not end with minus
          if [[ "$REPO" == *- ]]; then exit 1; fi
      - name: Get Token
        id: get-workflow-token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Create repo
        id: create-repo
        shell: bash
        env:
          GH_TOKEN: ${{ steps.get-workflow-token.outputs.token }}
          REPO_NAME: ${{ steps.generate-repo-name.outputs.name }}
        run: |
          url=$(gh repo create xpirit-training/${{ env.REPO_NAME }} --public)
          echo "repo_url=$url" >> "$GITHUB_OUTPUT"
      - name: Create comment and close issue on success
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue close ${{ github.event.issue.number }} -r Completed -c "@${{ github.event.issue.user.login }} your repository was created and is now accessible here: ${{ steps.create-repo.outputs.repo_url }}"
      - name: Create comment on failure
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -b "@${{ github.event.issue.user.login }} there were some problems provisioning your repo. Please reach out to your org owner for additional help. Thank you."  
          
