name: Create new repo based on a repo request 

on:
 issues:
    types: [labeled]

jobs:
  create-repos-from-issue:
    if: ${{ github.event.label.name == 'repo-request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Create repo
        id: create-repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ISSUEOPS_PAT }}
        run: |
          name=$(echo '${{ steps.parse.outputs.payload }}' | jq -r .Name)
          url=$(gh repo create xpirit-training/$name --public)
          echo "repo_url=$url" >> "$GITHUB_OUTPUT"
      - name: Create comment and close issue
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue close -r Completed -c "@${{ github.event.issue.author }} your repository was created and is now accessible here: $ {{ steps.create-repo.outputs.repo_url }}"
