name: Update the 'Repo-Request' Issue Template

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every night at midnight to update teams
  push:
    paths:
      - "./templates/languages/**"
      - ".github/workflows/update-repo-request-template.yml"

permissions:
  contents: write

env:
  ISSUE_TEMPLATE_FILE: .github/ISSUE_TEMPLATE/repo-request.yml

jobs:
  update-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Get Token
        id: get-workflow-token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_KEY }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Get Teams
        uses: ./.github/actions/get-teams
        id: get-teams
        with:
          token: ${{ steps.get-workflow-token.outputs.token }}
          organization: ${{ vars.ORGANIZATION }}
      - name: Update Teams
        env:
          JSON: ${{ steps.get-teams.outputs.json }}
        run: |
          TEAMS=$( echo $JSON \
            | jq -r '.[] | "- " + .name + (.description | if . == "" then . else " - " + . end )' \
            | sort ) \
            yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Team") | .attributes.options) |=env(TEAMS)' \
            $ISSUE_TEMPLATE_FILE
      - name: Update Languages
        run: |
          LANGUAGES=$( find ./templates/languages \
            -mindepth 1 \
            -maxdepth 1 \
            -type d \
            -exec sh \
            -c 'echo - $(basename "$1")' sh {} \; \
            | sort ) \
            yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Language") | .attributes.options) |=env(LANGUAGES)' \
            $ISSUE_TEMPLATE_FILE
      - name: Determine Changes
        id: change-detection
        run: |
          if (git diff --quiet $ISSUE_TEMPLATE_FILE)
          then 
            echo changed=false >> "$GITHUB_OUTPUT"
          else 
            echo changed=true >> "$GITHUB_OUTPUT"
          fi
      - name: Display File
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        run: cat $ISSUE_TEMPLATE_FILE
      - name: "Yamllint"
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ${{ env.ISSUE_TEMPLATE_FILE }}
          yamllint_strict: true
      - name: Commit Changes
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        env:
          CI_COMMIT_MESSAGE: "chore(org): Update Issue Template File"
        run: |
          git config --global user.name '${{ vars.CI_COMMIT_USER }}'
          git config --global user.email '${{ vars.CI_COMMIT_USER_MAIL }}'
          git add $ISSUE_TEMPLATE_FILE
          git commit -m "$CI_COMMIT_MESSAGE"
          git push
