name: Update the 'Repo-Request' issue template

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/org/**'

permissions:
  contents: write

env:
  ORG_FILE: .github/org/org-structure.yml
  ISSUE_TEMPLATE_FILE: .github/ISSUE_TEMPLATE/repo-request.yml

jobs:
  update-org:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Update Companies
        shell: bash
        run: >-
          COMPANIES=$(find .github/org/companies -mindepth 1 -maxdepth 1 -type d -exec sh -c 'basename "$0" | yq [.]' {} \; | sort)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Company") | .attributes.options) |=env(COMPANIES)'
          $ISSUE_TEMPLATE_FILE
      - name: Update Teams
        shell: bash
        run: >-
          TEAMS=$(find .github/org/companies/*/teams -mindepth 1 -maxdepth 1 -type d -exec sh -c 'basename "$0" | yq [.]' {} \; | sort)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Team") | .attributes.options) |=env(TEAMS)'
          $ISSUE_TEMPLATE_FILE
      - name: Update Projects
        shell: bash
        run: >-
          PROJECTS=$(find .github/org/companies/*/teams/*/projects -mindepth 1 -maxdepth 1 -type d -exec sh -c 'basename "$0" | yq [.]' {} \; | sort)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Project") | .attributes.options) |=env(PROJECTS)'
          $ISSUE_TEMPLATE_FILE
      - name: Display File
        shell: bash
        run: cat $ISSUE_TEMPLATE_FILE
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ${{ env.ISSUE_TEMPLATE_FILE }}
          yamllint_strict: true
      - name: Commit Changes
        env: 
          CI_COMMIT_MESSAGE: "chore(org): Update Issue Template File"
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "CI@users.noreply.github.com"
          git add $ISSUE_TEMPLATE_FILE
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
