name: Update the 'Repo-Request' issue template

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/org/**'
      - '.github/workflows/update-repo-request-template.yml'

permissions:
  contents: write

env:
  ORG_FILE: .github/org/org-structure.yml
  ISSUE_TEMPLATE_FILE: .github/ISSUE_TEMPLATE/repo-request.yml

jobs:
  update-org:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Get Companies
        run: >-
          find .github/org/companies -mindepth 1 -maxdepth 1 -type d -exec sh -c 'echo - $(basename "$1") \($(yq '.number' "$1"/metadata.yml)\)' sh {} \; | sort > companies
      - name: Get Teams
        run: >-
          find .github/org/companies/*/teams -mindepth 1 -maxdepth 1 -type d -exec sh -c 'echo - $(yq '.id' "$1"/metadata.yml)-$(basename "$1")' sh {} \; | sort > teams
      - name: Get Projects
        run: >-
          find .github/org/companies/*/teams/*/projects -mindepth 1 -maxdepth 1 -type d -exec sh -c 'echo - $(basename "$1")' sh {} \; | sort > projects
      - name: Update Companies
        run: >-
          COMPANIES=$(cat companies)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Company") | .attributes.options) |=env(COMPANIES)'
          $ISSUE_TEMPLATE_FILE
      - name: Update Teams
        run: >-
          TEAMS=$(cat teams)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Team") | .attributes.options) |=env(TEAMS)'
          $ISSUE_TEMPLATE_FILE
      - name: Update Projects
        run: >-
          PROJECTS=$(cat projects)
          yq -i '(.body[] | select(.type=="dropdown" and .attributes.label=="Project") | .attributes.options) |=env(PROJECTS)'
          $ISSUE_TEMPLATE_FILE
      - name: Determine Changes
        id: change-detection
        run: |
          if (git diff --quiet .github/ISSUE_TEMPLATE/repo-request.yml)
          then 
            echo changed=false >> "$GITHUB_OUTPUT"
          else 
            echo changed=true >> "$GITHUB_OUTPUT"
          fi
      - name: Display File
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        run: cat $ISSUE_TEMPLATE_FILE
      - name: 'Yamllint'
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ${{ env.ISSUE_TEMPLATE_FILE }}
          yamllint_strict: true
      - name: Commit Changes          
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        env: 
          CI_COMMIT_MESSAGE: "chore(org): Update Issue Template File"
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "xpirit-training-coach[bot]"
          git config --global user.email "139445269+xpirit-training-coach[bot]@users.noreply.github.com"
          git add $ISSUE_TEMPLATE_FILE
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
